#!/usr/bin/env python

import os, sys, time, urllib2, subprocess, StringIO
from datetime import datetime, date


# File settings

myhost			= os.uname()[1]
user			= "yourusers"
server			= "seedit1"	#in /etc/hosts
sshKey			= "~/.ssh/yourkey"
remotePath		= "/yourRemotePath" #path where to copy on the server
htmlPath		= "/yourhtlmPath" #pulibc path of the server
camera			= "camera01"
picStorage		= "/home/pi/projects/cameraIrLed/pictures"

# Save a full size image to disk
def saveImage():
	global camera
	time = datetime.now()
	picName = myhost + "-%02d%02d%04d-%02d%02d%02d.jpg" % (time.day, time.month, time.year, time.hour, time.minute, time.second)
	filename = picStorage + "/" + picName
	#to have a link to last pic taken on the server
	lastPicLink = picName
	# Take a shot
	subprocess.call("raspistill -w 800 -h 600 -t 1000 -awb auto -ex auto -e jpg -q 70 -o %s" % filename, shell=True)
	
	# Upload image to server via scp and link via ssh
	subprocess.call("/usr/bin/scp -i %s %s %s@%s:%s/%s/%s >/dev/null 2>&1" % (sshKey, filename, user, server, remotePath, myhost, camera), shell=True)
	
	subprocess.call("/usr/bin/ssh -i %s %s@%s ln -sf %s/%s/%s/%s %s/%s/%s/lastpic.jpg >/dev/null 2>&1"  % (sshKey, user, server, remotePath, myhost, camera, lastPicLink, htmlPath, myhost, camera), shell=True)


saveImage()