#!/bin/bash
#script to tar and copy the data to the server

sensorValues=/home/pi/projects/humTempScript/sensorValues/
measurements=/home/pi/projects/humTempScript/Measurements/

#go to log directory
cd $sensorValues >/dev/null 2>&1

sudo chown pi:pi *

#find and tar files modified between 24h and 48h
find . -type f  -mtime 1 | xargs tar czvf `hostname`-`date --date="2 days ago" +%d"-"%m"-"%Y`-RHT-measures.tar.gz >/dev/null 2>&1

#move the files to the $measurements folder
for f in `ls *tar.gz`; do 
	mv $f $measurements 
	scp -i ~/.ssh/yourkey $measurements$f youruser@yourserver:/yourpath/`hostname`/measurements/ >/dev/null 2>&1
done

#erase old log files
find . -type f  -mtime 5 -delete >/dev/null 2>&1
cd $measurements >/dev/null 2>&1
find . -type f  -mtime 29 -delete >/dev/null 2>&1